### ISSUE TITLE
Retry Github API Request

### ISSUE THREAD

**Issue by Joeoh** [Joeoh/GitMyStats#50]
Githubs API will sometimes return an empty response if they have not recently calculated the stats for a repository or user. Add a retry if an empty response is returned.

**Comment by barischj** [comment]
@cmcgarr what's the status on this?

**Comment by cmcgarr** [comment]
Currently it appears to enter the retry state more times than it should and there was an issue with the onsuccess method not being called. Will take another look at it now. Testing may have been the issue. github.contributors is the most updated version and others will be altered once i get it working.

**Comment by barischj** [comment]
@cmcgarr Can you confirm this is working again please.

**Comment by cmcgarr** [comment]
Still cant see my Retry Fix code in master. I do have the Retry Fix stored locally so i can merge that again if mine is the only code missing and that would solve the problem?

**Comment by barischj** [comment]
One minute. Let me investigate.

**Comment by barischj** [comment]
Close this yourself if you're semi-sure it works
