### ISSUE TITLE
Set date range in `commits-page`.

### ISSUE THREAD

**Issue by barischj** [Joeoh/GitMyStats#62]

**Comment by barischj** [comment]
This would be done in `github.commit_activity` and `github.participation`

**Comment by BlackAndWhiteSoldier** [comment]
done and feature has been merged.

**Comment by barischj** [comment]
@BlackAndWhiteSoldier You might have to do this again. Please put in a PR tonight. Should be straightforward since you already did it. See my comment in FB chat about visiting old code.
